apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: bW9uZ291c2Vy  # base64 of 'mongouser'
  mongo-root-password: c2VjdXJlcGFzcw==  # base64 of 'securepass'
