version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://admin:password@mongo:27017
      - PORT=3000
    depends_on:
      - mongo

volumes:
  mongo-data:
